version: "3.8"
services:
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: os-node
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 20

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.13.0
    container_name: os-dash
    environment:
      - OPENSEARCH_HOSTS=['http://opensearch:9200']
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
